-- Sample DepartmentLocation data
INSERT INTO DEPARTMENT_LOCATION (NAME) VALUES ('Headquarters');
INSERT INTO DEPARTMENT_LOCATION (NAME) VALUES ('Branch 1');
INSERT INTO DEPARTMENT_LOCATION (NAME) VALUES ('Branch 2');

-- Sample Department data
INSERT INTO DEPARTMENT (NAME, CODE, DESCRIPTION, DEPARTMENT_LOCATION_ID)
VALUES ('HR', 1, 'Human Resources Department', 1);
INSERT INTO DEPARTMENT (NAME, CODE, DESCRIPTION, DEPARTMENT_LOCATION_ID)
VALUES ('Finance', 2, 'Finance Department', 2);
INSERT INTO DEPARTMENT (NAME, CODE, DESCRIPTION, DEPARTMENT_LOCATION_ID)
VALUES ('Engineering', 3, 'Engineering Department', 3);

-- Sample Employee data

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, PHONE_NUMBER, SALARY, DEPARTMENT_ID)
SELECT 'John', 'Doe', '123-456-7890', 50000, 1 FROM SYSTEM_RANGE(1,1000);

INSERT INTO PROJECT (NAME, CODE, DEPARTMENT_ID)
SELECT 'Project', 1, 1 FROM SYSTEM_RANGE(1,1000);


-- Sample ProjectParticipation data

INSERT INTO PROJECT_PARTICIPATION (PROJECT_ID, JOINED_AT, EMPLOYEE_ID)
SELECT 1, CURRENT_TIMESTAMP, X.ID
FROM SYSTEM_RANGE(1, 1000) AS X(ID);