spring:
  datasource:
    url: jdbc:h2:/tmp/h2db/testdb;AUTO_SERVER=TRUE;INIT=create schema if not exists `jpa-module`;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true